[package]
name = "generic_iter"
version = "0.1.0"
edition = "2024"
publish = ["artifactory"]

[dependencies]
clap = { version = "4.6.6" }
orx-criterion = { version = "1.0.0" }
orx-parallel = { path = "../../../" }
bench-helper = { path = "../../bench-helper" }
rand = { version = "0.10.2" }
rand_chacha = { version = "0.10" }
rayon = { version = "1.12.0" }

[features]
seq = []
orx-once = []
orx-basic = ["orx-parallel/persistent-pool"]
orx-rayon = ["orx-parallel/persistent-pool-rayon"]
rayon = []
