[package]
name = "orx-parallel"
version = "4.0.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
readme = "README.md"
description = "High-performance, expressive, configurable parallel computations with an iterator-style API."
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-parallel/"
keywords = ["parallel", "concurrency", "performance", "thread", "iterator"]
categories = ["concurrency", "algorithms"]

[dependencies]
orx-iterable = { version = "1.3.0", default-features = false }
orx-pseudo-default = { version = "2.1.0", default-features = false }
orx-priority-queue = { version = "1.7.0", default-features = false }
orx-concurrent-iter = { version = "4.0.0", default-features = false }
orx-pinned-vec = { version = "4.0.0", default-features = false }
orx-fixed-vec = { version = "4.0.0", default-features = false }
orx-split-vec = { version = "4.0.0", default-features = false }
orx-pinned-concurrent-col = { version = "3.0.0", default-features = false }
orx-concurrent-bag = { version = "4.0.0", default-features = false }
orx-concurrent-ordered-bag = { version = "4.0.0", default-features = false }
# orx-concurrent-recursive-iter = { version = "3.0.0", default-features = false }
orx-concurrent-recursive-iter = { path = "/home/uarikan/orx/orx-concurrent-recursive-iter", default-features = false }

# optional: thread pool
rayon-core = { version = "1.13.0", optional = true, default-features = false }

# wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true, default-features = false }
js-sys = { version = "0.3", optional = true, default-features = false }

[dev-dependencies]
clap = { version = "4.6.5", features = ["derive"] }
orx-criterion = { version = "1.0.0" }
rand = { version = "0.10.2" }
rand_chacha = { version = "0.10" }
rayon = { version = "1.12.0" }
test-case = { version = "3.3.1" }


[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["std"]
std = ["orx-concurrent-recursive-iter/std"]
experimental = []
long-tests = []
wasm = ["std", "dep:wasm-bindgen", "dep:js-sys"]
persistent-pool-rayon = ["std", "rayon-core"]
persistent-pool = ["std"]


# examples

[[example]]
name = "recursive_tree"
path = "examples/recursive_tree/main.rs"
required-features = ["std"]

[[example]]
name = "use_impact_on_memory"
path = "examples/use_impact_on_memory/main.rs"

[[example]]
name = "diagnostics"
path = "examples/diagnostics.rs"
required-features = ["std"]

[[example]]
name = "enumerate"
path = "examples/enumerate.rs"
required-features = ["std"]

[[example]]
name = "fallible_option"
path = "examples/fallible_option.rs"
required-features = ["std"]

[[example]]
name = "fallible_result"
path = "examples/fallible_result.rs"
required-features = ["std"]

[[example]]
name = "iter_of_iter_collect"
path = "examples/iter_of_iter_collect.rs"
required-features = ["std"]

[[example]]
name = "iter_of_iter_reduce"
path = "examples/iter_of_iter_reduce.rs"
required-features = ["std"]

[[example]]
name = "max_num_threads_config"
path = "examples/max_num_threads_config.rs"
required-features = ["std"]

[[example]]
name = "par_mut"
path = "examples/par_mut.rs"
required-features = ["std"]

[[example]]
name = "recursive_file_system"
path = "examples/recursive_file_system.rs"
required-features = ["std"]

# benchmarks

## benchmarks - xap

[[bench]]
name = "xap-cf"
harness = false
path = "benches/xap/cf.rs"

[[bench]]
name = "xap-cmmmm"
harness = false
path = "benches/xap/cmmmm.rs"

[[bench]]
name = "xap-f"
harness = false
path = "benches/xap/f.rs"

[[bench]]
name = "xap-ff"
harness = false
path = "benches/xap/ff.rs"

[[bench]]
name = "xap-fff"
harness = false
path = "benches/xap/fff.rs"

[[bench]]
name = "xap-ffff"
harness = false
path = "benches/xap/ffff.rs"

[[bench]]
name = "xap-i"
harness = false
path = "benches/xap/i.rs"

[[bench]]
name = "xap-ii"
harness = false
path = "benches/xap/ii.rs"

[[bench]]
name = "xap-iii"
harness = false
path = "benches/xap/iii.rs"

[[bench]]
name = "xap-iiii"
harness = false
path = "benches/xap/iiii.rs"

[[bench]]
name = "xap-l-cons"
harness = false
path = "benches/xap/l_cons.rs"

[[bench]]
name = "xap-l-iter"
harness = false
path = "benches/xap/l_iter.rs"

[[bench]]
name = "xap-l-vec"
harness = false
path = "benches/xap/l_vec.rs"

[[bench]]
name = "xap-lf"
harness = false
path = "benches/xap/lf.rs"

[[bench]]
name = "xap-ll-cons"
harness = false
path = "benches/xap/ll_cons.rs"

[[bench]]
name = "xap-ll-iter"
harness = false
path = "benches/xap/ll_iter.rs"

[[bench]]
name = "xap-ll-vec"
harness = false
path = "benches/xap/ll_vec.rs"

[[bench]]
name = "xap-lll-cons"
harness = false
path = "benches/xap/lll_cons.rs"

[[bench]]
name = "xap-lll-iter"
harness = false
path = "benches/xap/lll_iter.rs"

[[bench]]
name = "xap-lll-vec"
harness = false
path = "benches/xap/lll_vec.rs"

[[bench]]
name = "xap-lm"
harness = false
path = "benches/xap/lm.rs"

[[bench]]
name = "xap-m"
harness = false
path = "benches/xap/m.rs"

[[bench]]
name = "xap-mf"
harness = false
path = "benches/xap/mf.rs"

[[bench]]
name = "xap-mfm"
harness = false
path = "benches/xap/mfm.rs"

[[bench]]
name = "xap-mfmf"
harness = false
path = "benches/xap/mfmf.rs"

[[bench]]
name = "xap-mfmfmf"
harness = false
path = "benches/xap/mfmfmf.rs"

[[bench]]
name = "xap-mm"
harness = false
path = "benches/xap/mm.rs"

[[bench]]
name = "xap-mmmm"
harness = false
path = "benches/xap/mmmm.rs"

## benchmarks - xap-pll

[[bench]]
name = "xap-pll-fff"
harness = false
path = "benches/xap_pll/fff.rs"

[[bench]]
name = "xap-pll-iii"
harness = false
path = "benches/xap_pll/iii.rs"

[[bench]]
name = "xap-pll-l-vec"
harness = false
path = "benches/xap_pll/l_vec.rs"

[[bench]]
name = "xap-pll-lf"
harness = false
path = "benches/xap_pll/lf.rs"

[[bench]]
name = "xap-pll-lfmi"
harness = false
path = "benches/xap_pll/lfmi.rs"

[[bench]]
name = "xap-pll-lfmli"
harness = false
path = "benches/xap_pll/lfmli.rs"

[[bench]]
name = "xap-pll-lfmli2"
harness = false
path = "benches/xap_pll/lfmli2.rs"

[[bench]]
name = "xap-pll-ll-vec"
harness = false
path = "benches/xap_pll/ll_vec.rs"

[[bench]]
name = "xap-pll-lll-vec"
harness = false
path = "benches/xap_pll/lll_vec.rs"

[[bench]]
name = "xap-pll-mmm"
harness = false
path = "benches/xap_pll/mmm.rs"
