[package]
name = "orx-parallel"
version = "3.4.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
readme = "README.md"
description = "High performance, configurable and expressive parallel computation library."
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-parallel/"
keywords = ["parallel", "concurrency", "performance", "thread", "iterator"]
categories = ["concurrency", "algorithms"]

[dependencies]
orx-iterable = { version = "1.3.0", default-features = false }
orx-pseudo-default = { version = "2.1.0", default-features = false }
orx-priority-queue = { version = "1.7.0", default-features = false }
orx-pinned-vec = { git = "https://github.com/orxfun/orx-pinned-vec", branch = "v4", default-features = false }
orx-fixed-vec = { git = "https://github.com/orxfun/orx-fixed-vec", branch = "v4", default-features = false }
orx-split-vec = { git = "https://github.com/orxfun/orx-split-vec", branch = "v4", default-features = false }
orx-concurrent-iter = { git = "https://github.com/orxfun/orx-concurrent-iter/", branch = "v4", default-features = false }
orx-concurrent-bag = { git = "https://github.com/orxfun/orx-concurrent-bag/", branch = "v4", default-features = false }
orx-concurrent-ordered-bag = { git = "https://github.com/orxfun/orx-concurrent-ordered-bag/", branch = "v4", default-features = false }
orx-pinned-concurrent-col = { git = "https://github.com/orxfun/orx-pinned-concurrent-col/", branch = "v3", default-features = false }
orx-concurrent-recursive-iter = { git = "https://github.com/orxfun/orx-concurrent-recursive-iter", branch = "v3", default-features = false }

# optional: generic iterator
rayon = { version = "1.11.0", optional = true, default-features = false }

# optional: thread pool
pond = { version = "0.3.1", optional = true, default-features = false }
poolite = { version = "0.7.1", optional = true, default-features = false }
rayon-core = { version = "1.13.0", optional = true, default-features = false }
scoped-pool = { version = "1.0.0", optional = true, default-features = false }
scoped_threadpool = { version = "0.1.9", optional = true, default-features = false }
yastl = { version = "0.1.2", optional = true, default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true, default-features = false }
js-sys = { version = "0.3", optional = true, default-features = false }

[target.'cfg(all(target_arch = "wasm32", target_feature = "atomics"))'.dependencies]
wasm-bindgen-rayon = { version = "1.3", optional = true, default-features = false }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"

[dev-dependencies]
chili = "0.2"
chrono = "0.4.42"
clap = { version = "4.5.50", features = ["derive"] }
enum-iterator = { version = "2.3.0", default-features = false }
orx-concurrent-option = { version = "1.5.0", default-features = false }
orx-concurrent-vec = { git = "https://github.com/orxfun/orx-concurrent-vec", branch = "v4", default-features = false }
orx-criterion = { git = "https://github.com/orxfun/orx-criterion" }
orx-imp-vec = { version = "2.17.0" }
paralight = "0.0.7"
rand = "0.9.2"
rand_chacha = "0.9"
rayon = "1.11.0"
test-case = "3.3.1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[package.metadata.docs.rs]
all-features = true

[features]
default = ["std", "rayon-core", "rayon"]
std = ["orx-concurrent-recursive-iter/std"]
experimental = []
long-tests = []
wasm = ["std", "dep:wasm-bindgen", "dep:js-sys"]
wasm-experimental = [
    "std",
    "rayon-core",
    "dep:wasm-bindgen",
    "dep:js-sys",
    "dep:wasm-bindgen-rayon",
]


# examples

[[example]]
name = "diagnostics"
path = "examples/diagnostics.rs"
required-features = ["std"]

[[example]]
name = "het"
path = "examples/het.rs"
required-features = ["rayon-core"]

[[example]]
name = "het_advanced"
path = "examples/het_advanced.rs"
required-features = ["std"]

[[example]]
name = "het_advanced2"
path = "examples/het_advanced2.rs"
required-features = ["std"]

[[example]]
name = "recursive-tree"
path = "examples/recursive_tree/main.rs"

# benchmarks

## benchmarks - heterogeneity

[[bench]]
name = "het-simple"
harness = false
path = "benches/het/simple.rs"
required-features = ["std"]

[[bench]]
name = "het-advanced"
harness = false
path = "benches/het/advanced.rs"
required-features = ["std"]

## benchmarks - recursive

[[bench]]
name = "rec-file-system"
harness = false
path = "benches/rec/file_system.rs"
required-features = ["rayon-core"]

## benchmarks - runner

[[bench]]
name = "runner-mf-r"
harness = false
path = "benches/runner/mf_r.rs"
required-features = ["rayon-core"]

## benchmarks - first

[[bench]]
name = "first-f"
harness = false
path = "benches/first/f.rs"

[[bench]]
name = "first-ff"
harness = false
path = "benches/first/ff.rs"

[[bench]]
name = "first-fff"
harness = false
path = "benches/first/fff.rs"

[[bench]]
name = "first-i"
harness = false
path = "benches/first/i.rs"

[[bench]]
name = "first-id"
harness = false
path = "benches/first/id.rs"

[[bench]]
name = "first-lf"
harness = false
path = "benches/first/lf.rs"

[[bench]]
name = "first-mf"
harness = false
path = "benches/first/mf.rs"

[[bench]]
name = "first-mfmf"
harness = false
path = "benches/first/mfmf.rs"

[[bench]]
name = "first-mi"
harness = false
path = "benches/first/mi.rs"

## benchmarks - collect

[[bench]]
name = "collect-f"
harness = false
path = "benches/collect/f.rs"

[[bench]]
name = "collect-id"
harness = false
path = "benches/collect/id.rs"

[[bench]]
name = "collect-l"
harness = false
path = "benches/collect/l.rs"

[[bench]]
name = "collect-m"
harness = false
path = "benches/collect/m.rs"

[[bench]]
name = "collect-mf"
harness = false
path = "benches/collect/mf.rs"
required-features = ["std"]

[[bench]]
name = "collect-mfm"
harness = false
path = "benches/collect/mfm.rs"

[[bench]]
name = "collect-mfmf"
harness = false
path = "benches/collect/mfmf.rs"

## benchmarks - reduce

[[bench]]
name = "reduce-f"
harness = false
path = "benches/reduce/f.rs"

[[bench]]
name = "reduce-id"
harness = false
path = "benches/reduce/id.rs"

[[bench]]
name = "reduce-l"
harness = false
path = "benches/reduce/l.rs"

[[bench]]
name = "reduce-m"
harness = false
path = "benches/reduce/m.rs"

[[bench]]
name = "reduce-mf"
harness = false
path = "benches/reduce/mf.rs"

[[bench]]
name = "reduce-mfm"
harness = false
path = "benches/reduce/mfm.rs"

[[bench]]
name = "reduce-mfmf"
harness = false
path = "benches/reduce/mfmf.rs"

## benchmarks - throughput_linear

[[bench]]
name = "throughput-linear-log-collect"
harness = false
path = "benches/throughput_linear/log_collect.rs"
required-features = ["std"]

[[bench]]
name = "throughput-linear-log-reduce"
harness = false
path = "benches/throughput_linear/log_reduce.rs"
required-features = ["std"]

## benchmarks - early_exit

[[bench]]
name = "early-exit-suspicious-first"
harness = false
path = "benches/early_exit/suspicious_first.rs"
required-features = ["std"]

[[bench]]
name = "early-exit-suspicious-find-any"
harness = false
path = "benches/early_exit/suspicious_find_any.rs"
required-features = ["std"]

## benchmarks - fallible

[[bench]]
name = "fallible-validation-result"
harness = false
path = "benches/fallible/validation_result.rs"
required-features = ["std"]

[[bench]]
name = "fallible-validation-option"
harness = false
path = "benches/fallible/validation_option.rs"
required-features = ["std"]

## benchmarks - stateful_using

[[bench]]
name = "stateful-using-monte-carlo-batch"
harness = false
path = "benches/stateful_using/monte_carlo_batch.rs"
required-features = ["std"]
