use crate::Params;
use crate::collectables::alg::merge_collected::merge_arb_into_vec;
use crate::infallible::recursive::execution::collect_arb::collect_arb;
use crate::infallible::recursive::execution::tests::tree::{Node, flatten};
use crate::infallible::{Xap, xap_variants::Id};
use crate::runner::default_runner;
use alloc::vec::Vec;
use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;
use test_case::test_matrix;
