[package]
name = "wasm_bindings"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
computation = { path = "../computation", features = ["wasm"] }
js-sys = "0.3"
orx-parallel = { path = "../../../../..", default-features = false, features = [
    "wasm",
] }
wasm-bindgen = "0.2"
